### ISSUE TITLE
ImportError: cannot import name 'ArgSpec' from 'inspect' 

### ISSUE THREAD

**Issue by Abhiz2411** [agronholm/sqlacodegen#326]
### Things to check first

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Sqlacodegen version

2.3.0.post1

### SQLAlchemy version

1.4.52

### RDBMS vendor

PostgreSQL

### What happened?

When I ran the command `sqlacodegen postgresql://postgres:secret_pass@localhost:5432/db_name > model.py` It should have created code in model.py. I researched about the error and I think it is caused because codegen.py has an import statement `from inspect import ArgSpec` where `ArgSpec` is depreciated for python 3.12.2. I am using 3.12.2 version of python

**Comment by trembel** [comment]
For me it is solved using the rc version. Try `pip install sqlacodegen==3.0.0rc5`

**Comment by rafalkrupinski** [comment]
The last stable release is from 2020 and declares requirement on python 3.8
The latest python it actually works is 3.10
I use pipx and pyenv, so no problem. uv should handle it too.

**Comment by Abhiz2411** [comment]
Thanks. Will give it a shot

**Comment by sheinbergon** [comment]
@Abhiz2411 as mentioned earlier, latest 3.0.0rc5 does support python 3.12. 
We are currently actively working on a stable 3.0.x release

**Comment by agronholm** [comment]
The reason I pinned this issue is because people who don't know about pre-releases keep re-reporting this.

**Comment by agronholm** [comment]
But admittedly closing it doesn't unpin it, so let's hope people coming in to report this can still find it.

**Comment by kdipippo** [comment]
Confirming I was able to find this issue when I encountered this error just now after it's been closed 13 hours ago. `3.0.0rc5` worked perfectly
