### ISSUE TITLE
Can't generate code for PostgreSQL tables with Identity column

### ISSUE THREAD

**Issue by devspacenine** [agronholm/sqlacodegen#131]
I am getting the following error when I try to generate models for PostgreSQL tables that use the Identity type for primary key columns instead of Serial.

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlacodegen", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sqlacodegen/main.py", line 53, in main
    generator.render(outfile)
  File "/usr/local/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 727, in render
    rendered_models.append(self.render_class(model))
  File "/usr/local/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 707, in render_class
    self.indentation, attr, self.render_column(column, show_name))
  File "/usr/local/lib/python3.6/site-packages/sqlacodegen/codegen.py", line 601, in render_column
    default_expr = self._get_compiled_expression(column.server_default.arg)
AttributeError: 'Identity' object has no attribute 'arg'
```

sqlalchemy - 1.4.6
psycopg2   - 2.8.6
Postgres 11

**Comment by devspacenine** [comment]
I assume this package does not work with sqlalchemy 1.4.x yet?

**Comment by arobbins805** [comment]
I'm getting the same error:
```
Traceback (most recent call last):
  File "/home/adminuser/envs/sqlalchemy-test-env/bin/sqlacodegen", line 8, in <module>
    sys.exit(main())
  File "/home/adminuser/envs/sqlalchemy-test-env/lib/python3.7/site-packages/sqlacodegen/main.py", line 53, in main
    generator.render(outfile)
  File "/home/adminuser/envs/sqlalchemy-test-env/lib/python3.7/site-packages/sqlacodegen/codegen.py", line 729, in render
    rendered_models.append(self.render_table(model))
  File "/home/adminuser/envs/sqlalchemy-test-env/lib/python3.7/site-packages/sqlacodegen/codegen.py", line 638, in render_table
    rendered += '{0}{1},\n'.format(self.indentation, self.render_column(column, True))
  File "/home/adminuser/envs/sqlalchemy-test-env/lib/python3.7/site-packages/sqlacodegen/codegen.py", line 601, in render_column
    default_expr = self._get_compiled_expression(column.server_default.arg)
AttributeError: 'Identity' object has no attribute 'arg'
```
pyodbc             4.0.30
sqlacodegen        2.3.0
SQLAlchemy         1.4.7

**Comment by Freewilly3d** [comment]
This same error occurs on sql server identity columns.

**Comment by SkyLeach** [comment]
Ditto @Freewilly3d 

Unable to *generate* the reflected schema.

```python

Overwriting __init__.py...
Traceback (most recent call last):
  File "C:\Users\mattg\src\caregility\schema_database_work\ugly_raw_datascrape.py", line 216, in <module>
    DatabaseConnHelper().genReflectedSchema(args.modname)
  File "C:\Users\mattg\src\caregility\schema_database_work\ugly_raw_datascrape.py", line 136, in genReflectedSchema
    gen.render(outfile)
  File "C:\Python39\lib\site-packages\sqlacodegen\codegen.py", line 727, in render
    rendered_models.append(self.render_class(model))
  File "C:\Python39\lib\site-packages\sqlacodegen\codegen.py", line 707, in render_class
    self.indentation, attr, self.render_column(column, show_name))
  File "C:\Python39\lib\site-packages\sqlacodegen\codegen.py", line 601, in render_column
    default_expr = self._get_compiled_expression(column.server_default.arg)
AttributeError: 'Identity' object has no attribute 'arg'
```

**Comment by SkyLeach** [comment]
I don't know about the rest of you, but my problem was caused by MSSQL's latest version.  The problem is related to not specifying the database itself, only the server/host.  sqlacodegen will git a list of the schemas and then try to switch to each and reflect.  That will fail.

**Comment by agronholm** [comment]
> That will fail.

Why?

**Comment by agronholm** [comment]
Have you tried with the latest beta? If that fails, I'd be interested in knowing why.

**Comment by alexanderluiscampino** [comment]
How come this was closed without resolution?

**Comment by agronholm** [comment]
Without resolution? I added support for Identity columns so I closed the issue. I even asked users if it worked for them, but nobody replied. And now you're complaining?

**Comment by alexanderluiscampino** [comment]
I apologize for my lack of awareness, but reading this thread it does not look like a resolution had been found. It was more a situation of the error still occurring for me, with the latest version, and the thread being closed. 

Maybe, for future users that fall into the same problem,  how come the specification of the schema resolves the issue but if you run on all schemas the error is still raised?

**Comment by agronholm** [comment]
> I apologize for my lack of awareness, but reading this thread it does not look like a resolution had been found

![image](https://user-images.githubusercontent.com/130003/129441457-62aac122-36d7-4ff8-91f9-8c9cb10dd754.png)

In case you don't know what the above means, it means that commit d0ba5cb closed the issue. Meaning a fix was added to the repository. And this fix has been included in the 3.0.0b1 release.

> how come the specification of the schema resolves the issue but if you run on all schemas the error is still raised?

What do you mean, run on all schemas? There is no way to do that. If you don't specify any schemas explicitly, it will run against the default search path which typically only includes the default schema. If you know of a way to discover all the schemas with SQLAlchemy, do let me know!

**Comment by agronholm** [comment]
There is an issue with Identity columns, but it's different – see #150.

**Comment by agronholm** [comment]
Try 3.0.0b2 and see if it fixes the problem for you.

**Comment by UNOWEN-OwO** [comment]
3.0.0b2 worked for me

**Comment by wangmarkqi** [comment]
pip install sqlacodegen==3.0.0b2  
worked for me

**Comment by srafay** [comment]
Works in ```3.0.0b2```
pip install sqlacodegen==3.0.0b2
